FROM jupyter/pyspark-notebook:latest

USER root

# Installer Hadoop AWS et Boto3 pour la gestion de S3
RUN pip install boto3 && \
    wget -P /usr/local/spark/jars/ \
    https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.1/hadoop-aws-3.3.1.jar && \
    wget -P /usr/local/spark/jars/ \
    https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.11.901/aws-java-sdk-bundle-1.11.901.jar
USER jovyan
