services:
  db:
    container_name: backend_db_mlflow
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres_db
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5430:5432
    networks:
      - backend_db_mlflow

networks:
  backend_db_mlflow:
    driver: bridge

volumes:
  postgresql_data:
    driver: local 
